### ISSUE TITLE
Navbar wireframe

### ISSUE THREAD

**Issue by ben-horner-dev** [ben-horner-dev/portfolio#2]
### User Story
As a user, I want a clear and accessible navigation bar that allows me to easily browse different sections or pages of the portfolio site, providing intuitive links for seamless navigation and exploration. 

### Acceptance Criteria
- [ ] Logo on the left
- [ ] Buttons for testimonials, contact
- [ ] Responsive

### Tasks
- [ ] Create wireframe in figma

### Additional Information (if any)
- Use existing brand assets

**Comment by vanessamontenegro87** [comment]
https://www.figma.com/file/fEDfWL6Nhc45QrQDj9vesu/BH-Dev-wireframe?type=design&node-id=0%3A1&mode=design&t=D3dS4uwCif9fpRlQ-1
