### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by ben-horner-dev** [ben-horner-dev/portfolio#6]
### User Story
1. As a visitor, I want a user-friendly contact form to easily reach out to the site owner or support team for inquiries or assistance.
2. As a logged-in user, I want my email address pre-populated in the contact form for convenience and accuracy.
3. As a Non logged in user display error that user must be logged in to send an email

### Acceptance Criteria
- [ ] small textfield for email address
- [ ] large textfield for message content
- [ ] A send btn
- [ ] Flash message in MUI Alert style (red) at the top of the screen

### Tasks
- [ ] Create wireframe

### Additional Information (if any)
Use Existing brand assets, color pallette and fonts
